# Generated by Django 4.2.7 on 2023-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_team_alter_frequent_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='team',
            name='num_hierarquical',
            field=models.IntegerField(default=0),
        ),
    ]
