# Generated by Django 4.2.7 on 2023-12-09 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_contact_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrocel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='website/galeria/')),
                ('title', models.CharField(max_length=255)),
                ('local', models.CharField(choices=[('HOME', 'HOME'), ('SOBRE', 'SOBRE'), ('CANDIDATURA', 'CANDIDATURA')], max_length=25)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='website/galeria/')),
                ('title', models.CharField(max_length=255)),
                ('image_description', models.CharField(default='', max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Frequent_Question',
            new_name='FrequentQuestion',
        ),
        migrations.RenameModel(
            old_name='News_Category',
            new_name='NewsCategory',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['email', 'name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
