# Generated by Django 4.2.7 on 2023-12-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_team_function'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['num_hierarquical', 'name']},
        ),
        migrations.RenameField(
            model_name='newscategory',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='newscategory',
            name='content',
        ),
    ]
