# Generated by Django 4.2.7 on 2023-12-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrocel',
            name='local',
            field=models.CharField(choices=[('HOME', 'HOME'), ('SOBRE', 'SOBRE'), ('CANDIDATURA', 'CANDIDATURA'), ('NOTICIAS', 'NOTICIAS')], max_length=25),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=125)),
                ('content', models.TextField(max_length=255)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='website.new')),
            ],
        ),
    ]
